/**
 */
package idm.simplemarkdown.mm.simplemarkdown.provider;

import idm.simplemarkdown.mm.simplemarkdown.util.SimplemarkdownAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SimplemarkdownItemProviderAdapterFactory extends SimplemarkdownAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SimplemarkdownItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Document} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentItemProvider documentItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Document}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDocumentAdapter() {
		if (documentItemProvider == null) {
			documentItemProvider = new DocumentItemProvider(this);
		}

		return documentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Paragraph} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ParagraphItemProvider paragraphItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Paragraph}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createParagraphAdapter() {
		if (paragraphItemProvider == null) {
			paragraphItemProvider = new ParagraphItemProvider(this);
		}

		return paragraphItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Title} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TitleItemProvider titleItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Title}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTitleAdapter() {
		if (titleItemProvider == null) {
			titleItemProvider = new TitleItemProvider(this);
		}

		return titleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Text} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextItemProvider textItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Text}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTextAdapter() {
		if (textItemProvider == null) {
			textItemProvider = new TextItemProvider(this);
		}

		return textItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.StrongEmphasis} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StrongEmphasisItemProvider strongEmphasisItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.StrongEmphasis}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStrongEmphasisAdapter() {
		if (strongEmphasisItemProvider == null) {
			strongEmphasisItemProvider = new StrongEmphasisItemProvider(this);
		}

		return strongEmphasisItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Code} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeItemProvider codeItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Code}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeAdapter() {
		if (codeItemProvider == null) {
			codeItemProvider = new CodeItemProvider(this);
		}

		return codeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.BulletList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BulletListItemProvider bulletListItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.BulletList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBulletListAdapter() {
		if (bulletListItemProvider == null) {
			bulletListItemProvider = new BulletListItemProvider(this);
		}

		return bulletListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.BulletListItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BulletListItemItemProvider bulletListItemItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.BulletListItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBulletListItemAdapter() {
		if (bulletListItemItemProvider == null) {
			bulletListItemItemProvider = new BulletListItemItemProvider(this);
		}

		return bulletListItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Link} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkItemProvider linkItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Link}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkAdapter() {
		if (linkItemProvider == null) {
			linkItemProvider = new LinkItemProvider(this);
		}

		return linkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Folder} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FolderItemProvider folderItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Folder}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFolderAdapter() {
		if (folderItemProvider == null) {
			folderItemProvider = new FolderItemProvider(this);
		}

		return folderItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.OrderedList} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrderedListItemProvider orderedListItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.OrderedList}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrderedListAdapter() {
		if (orderedListItemProvider == null) {
			orderedListItemProvider = new OrderedListItemProvider(this);
		}

		return orderedListItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.OrderedListItem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrderedListItemItemProvider orderedListItemItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.OrderedListItem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrderedListItemAdapter() {
		if (orderedListItemItemProvider == null) {
			orderedListItemItemProvider = new OrderedListItemItemProvider(this);
		}

		return orderedListItemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.BlockQuote} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BlockQuoteItemProvider blockQuoteItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.BlockQuote}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBlockQuoteAdapter() {
		if (blockQuoteItemProvider == null) {
			blockQuoteItemProvider = new BlockQuoteItemProvider(this);
		}

		return blockQuoteItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Image} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ImageItemProvider imageItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Image}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createImageAdapter() {
		if (imageItemProvider == null) {
			imageItemProvider = new ImageItemProvider(this);
		}

		return imageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Emphasis} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmphasisItemProvider emphasisItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Emphasis}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEmphasisAdapter() {
		if (emphasisItemProvider == null) {
			emphasisItemProvider = new EmphasisItemProvider(this);
		}

		return emphasisItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.CodeBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeBlockItemProvider codeBlockItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.CodeBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeBlockAdapter() {
		if (codeBlockItemProvider == null) {
			codeBlockItemProvider = new CodeBlockItemProvider(this);
		}

		return codeBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.HorizontalLine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HorizontalLineItemProvider horizontalLineItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.HorizontalLine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHorizontalLineAdapter() {
		if (horizontalLineItemProvider == null) {
			horizontalLineItemProvider = new HorizontalLineItemProvider(this);
		}

		return horizontalLineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.CodeLine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CodeLineItemProvider codeLineItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.CodeLine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCodeLineAdapter() {
		if (codeLineItemProvider == null) {
			codeLineItemProvider = new CodeLineItemProvider(this);
		}

		return codeLineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.LinkWithRef} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkWithRefItemProvider linkWithRefItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.LinkWithRef}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkWithRefAdapter() {
		if (linkWithRefItemProvider == null) {
			linkWithRefItemProvider = new LinkWithRefItemProvider(this);
		}

		return linkWithRefItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.Reference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReferenceItemProvider referenceItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.Reference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReferenceAdapter() {
		if (referenceItemProvider == null) {
			referenceItemProvider = new ReferenceItemProvider(this);
		}

		return referenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.TableBlock} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableBlockItemProvider tableBlockItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.TableBlock}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableBlockAdapter() {
		if (tableBlockItemProvider == null) {
			tableBlockItemProvider = new TableBlockItemProvider(this);
		}

		return tableBlockItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.TableRow} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableRowItemProvider tableRowItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.TableRow}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableRowAdapter() {
		if (tableRowItemProvider == null) {
			tableRowItemProvider = new TableRowItemProvider(this);
		}

		return tableRowItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.TableHead} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableHeadItemProvider tableHeadItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.TableHead}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableHeadAdapter() {
		if (tableHeadItemProvider == null) {
			tableHeadItemProvider = new TableHeadItemProvider(this);
		}

		return tableHeadItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.TableBody} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableBodyItemProvider tableBodyItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.TableBody}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableBodyAdapter() {
		if (tableBodyItemProvider == null) {
			tableBodyItemProvider = new TableBodyItemProvider(this);
		}

		return tableBodyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.TableSeparator} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableSeparatorItemProvider tableSeparatorItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.TableSeparator}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableSeparatorAdapter() {
		if (tableSeparatorItemProvider == null) {
			tableSeparatorItemProvider = new TableSeparatorItemProvider(this);
		}

		return tableSeparatorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link idm.simplemarkdown.mm.simplemarkdown.TableCell} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TableCellItemProvider tableCellItemProvider;

	/**
	 * This creates an adapter for a {@link idm.simplemarkdown.mm.simplemarkdown.TableCell}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTableCellAdapter() {
		if (tableCellItemProvider == null) {
			tableCellItemProvider = new TableCellItemProvider(this);
		}

		return tableCellItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (documentItemProvider != null)
			documentItemProvider.dispose();
		if (paragraphItemProvider != null)
			paragraphItemProvider.dispose();
		if (titleItemProvider != null)
			titleItemProvider.dispose();
		if (textItemProvider != null)
			textItemProvider.dispose();
		if (strongEmphasisItemProvider != null)
			strongEmphasisItemProvider.dispose();
		if (codeItemProvider != null)
			codeItemProvider.dispose();
		if (bulletListItemProvider != null)
			bulletListItemProvider.dispose();
		if (bulletListItemItemProvider != null)
			bulletListItemItemProvider.dispose();
		if (linkItemProvider != null)
			linkItemProvider.dispose();
		if (folderItemProvider != null)
			folderItemProvider.dispose();
		if (orderedListItemProvider != null)
			orderedListItemProvider.dispose();
		if (orderedListItemItemProvider != null)
			orderedListItemItemProvider.dispose();
		if (blockQuoteItemProvider != null)
			blockQuoteItemProvider.dispose();
		if (imageItemProvider != null)
			imageItemProvider.dispose();
		if (emphasisItemProvider != null)
			emphasisItemProvider.dispose();
		if (codeBlockItemProvider != null)
			codeBlockItemProvider.dispose();
		if (horizontalLineItemProvider != null)
			horizontalLineItemProvider.dispose();
		if (codeLineItemProvider != null)
			codeLineItemProvider.dispose();
		if (linkWithRefItemProvider != null)
			linkWithRefItemProvider.dispose();
		if (referenceItemProvider != null)
			referenceItemProvider.dispose();
		if (tableBlockItemProvider != null)
			tableBlockItemProvider.dispose();
		if (tableRowItemProvider != null)
			tableRowItemProvider.dispose();
		if (tableHeadItemProvider != null)
			tableHeadItemProvider.dispose();
		if (tableBodyItemProvider != null)
			tableBodyItemProvider.dispose();
		if (tableSeparatorItemProvider != null)
			tableSeparatorItemProvider.dispose();
		if (tableCellItemProvider != null)
			tableCellItemProvider.dispose();
	}

}
