// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model Complet;



/************************************************************/
/**
 * 
 */
public class Application {
	/**
	 * 
	 * @return 
	 * @param Volountary 
	 */
	public boolean isVolountary(Voluntary Volountary) {
	}
	/**
	 * 
	 */
	public void chooseActivity() {
	}
	/**
	 * 
	 */
	public void chooseActivity() {
	}
	/**
	 * 
	 * @return 
	 * @param voluntary 
	 */
	public boolean isVolountary(Identification_du_benevole.Voluntary voluntary) {
	}
	/**
	 * 
	 * @param nameOfBook 
	 * @return 
	 */
	public Book findBook(EcorePrimitiveTypes.EString nameOfBook) {
	}
	/**
	 * 
	 * @return 
	 */
	public Book selectAllBooks() {
	}
	/**
	 * 
	 * @param firstName 
	 * @param lastName 
	 */
	public void showStudentInfos(EcorePrimitiveTypes.EString firstName, EcorePrimitiveTypes.EString lastName) {
	}
	/**
	 * 
	 * @return 
	 */
	public Book selectBook() {
	}
	/**
	 * 
	 * @return 
	 */
	public Book[] showBorrowableBooks() {
	}
	/**
	 * 
	 * @param Student 
	 * @return 
	 */
	public EcorePrimitiveTypes.EBoolean canReturnBail(Student Student) {
	}
	/**
	 * 
	 * @return 
	 * @param student 
	 * @param booksStudentReturns 
	 */
	public boolean allBooksWereRetourned(Student student, RendreTousLesLivres.Book[] booksStudentReturns) {
	}
	/**
	 * 
	 * @return 
	 * @param student 
	 * @param booksStudentReturns 
	 */
	public RendreTousLesLivres.Book[] BooksThatWereNotRetourned(Student student, RendreTousLesLivres.Book[] booksStudentReturns) {
	}
	/**
	 * 
	 * @param student 
	 */
	public void sendMailMissingBooks(Student student) {
	}
	/**
	 * 
	 * @param books 
	 * @param student 
	 */
	public void booksReturnedByStudent(RendreTousLesLivres.Book books, Student student) {
	}
	/**
	 * 
	 */
	public void showHdfAmount() {
	}
	/**
	 * 
	 */
	public void showPrice() {
	}
	/**
	 * 
	 */
	public void showDepositAmount() {
	}
	/**
	 * 
	 */
	public void showEachPayment() {
	}
	/**
	 * 
	 * @return 
	 */
	public PremiereInscription.Book[] createBookList() {
	}
	/**
	 * 
	 */
	public void askForAction() {
	}
	/**
	 * 
	 * @param book 
	 */
	public void addNewBook(PremiereInscription.Book book) {
	}
	/**
	 * 
	 */
	public void askSignInForm() {
	}
	/**
	 * 
	 */
	public void askForName() {
	}
	/**
	 * 
	 * @param firstName 
	 * @param lastName 
	 */
	public void verifyParentName(String firstName, String lastName) {
	}
	/**
	 * 
	 * @param firstName 
	 * @param lastName 
	 */
	public void verifySignIn(String firstName, String lastName) {
	}
	/**
	 * 
	 */
	public void showMembership() {
	}
	/**
	 * 
	 * @param name 
	 */
	public void showMembershipList(String name) {
	}
	/**
	 * 
	 * @param firstName 
	 * @param lastName 
	 */
	public void searchForBrotherSisterName(String firstName, String lastName) {
	}
	/**
	 * 
	 */
	private void showNoPayment() {
	}
	/**
	 * 
	 */
	public void linkSheets() {
	}
};
