// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model Complet;



/************************************************************/
/**
 * 
 */
public class Book {
				/**
				 * 
				 */
				public BookState state;
				/**
				 * 
				 */
				public Retrait_des_livres.BookState state;
				/**
				 * 
				 */
				public EcorePrimitiveTypes.EInt price;
	/**
	 * 
	 */
	public void changeState() {
	}
	/**
	 * 
	 * @return 
	 */
	public BookState checkState() {
	}
	/**
	 * 
	 */
	public void changeState() {
	}
	/**
	 * 
	 * @return 
	 */
	public Retrait_des_livres.BookState checkState() {
	}
};
