// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model Complet;



/************************************************************/
/**
 * 
 */
public enum BookState {
	/**
	 * 
	 */
	borrowable,
	/**
	 * 
	 */
	toPrepare,
	/**
	 * 
	 */
	borrowable,
	/**
	 * 
	 */
	toPrepare
	;
};
