// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model Complet;



/************************************************************/
/**
 * 
 */
public class User {
				/**
				 * 
				 */
				protected EcorePrimitiveTypes.EString firstName;
				/**
				 * 
				 */
				protected EcorePrimitiveTypes.EString lastName;
				/**
				 * 
				 */
				protected EcorePrimitiveTypes.EString login;
				/**
				 * 
				 */
				protected EcorePrimitiveTypes.EString password;
				/**
				 * 
				 */
				protected EcorePrimitiveTypes.EString lastName;
				/**
				 * 
				 */
				protected EcorePrimitiveTypes.EString firstName;
};
