// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model

Complet;

/************************************************************/
/**
 * 
 */
public class Voluntary extends User {
	/**
	 * 
	 */
	private String login;
	/**
	 * 
	 */
	private String password;
	/**
	 * 
	 */
	private String lastName;
	/**
	 * 
	 */
	private String firstName;
	/**
	 * 
	 */
	protected EcorePrimitiveTypes.EString password;
	/**
	 * 
	 */
	protected EcorePrimitiveTypes.EString login;

	/**
	 * 
	 */
	public void logIn() {
	}

	/**
	 * 
	 */
	public void logIn() {
	}

	/**
	 * 
	 * @param student 
	 * @param summary 
	 */
	public void sendSummary(Student student, Summary summary) {
	}

	/**
	 * 
	 * @param student 
	 */
	public void searchStudent(Student student) {
	}

	/**
	 * 
	 */
	public void takeBookInventory() {
	}

	/**
	 * 
	 * @param student 
	 */
	public void returnTheDeposit(Model Complet.Student student) {
	}

	/**
	 * 
	 * @param student 
	 * @param price 
	 */
	public void makeStudentPay(RendreTousLesLivres.Student student, EcorePrimitiveTypes.EInt price) {
	}

	/**
	 * 
	 * @param student 
	 */
	public void searchStudent(Student student) {
	}

	/**
	 * 
	 */
	public void askMeanOfPayment() {
	}

	/**
	 * 
	 */
	public void tellPrice() {
	}

	/**
	 * 
	 */
	public void tidySheet() {
	}

	/**
	 * 
	 * @param check 
	 */
	public void fillCheckNumber(Check check) {
	}

	/**
	 * 
	 */
	public void askDeposit() {
	}

	/**
	 * 
	 */
	public void printMemberSheet() {
	}

	/**
	 * 
	 */
	public void giveSheet() {
	}

	/**
	 * 
	 * @param payment 
	 * @param amount 
	 */
	public void selectMeansOfPayment(Payment payment, float amount) {
	}

	/**
	 * 
	 */
	public void makeSign() {
	}

	/**
	 * 
	 */
	public void autorizeBookRecovery() {
	}

	/**
	 * 
	 */
	public void askForBrothersAndSisters() {
	}

	/**
	 * 
	 */
	public void askForBooks() {
	}

	/**
	 * 
	 */
	public void chooseAction() {
	}

	/**
	 * 
	 * @param amount 
	 */
	private void fillDonation(float amount) {
	}

	/**
	 * 
	 */
	public void chooseStudyingLevel() {
	}

	/**
	 * 
	 */
	public void askForDonation() {
	}

	/**
	 * 
	 */
	public void askForFields() {
	}

	/**
	 * 
	 */
	public void askForName() {
	}

	/**
	 * 
	 * @param firstName 
	 * @param lastName 
	 */
	private void fillName(String firstName, String lastName) {
	}

	/**
	 * 
	 */
	private void fillSubscription() {
	}

	/**
	 * 
	 * @param amount 
	 */
	public void askForContribution(float amount) {
	}

	/**
	 * 
	 */
	public void askForSubscription() {
	}

	/**
	 * 
	 * @param chosenTools 
	 */
	private void fillOptionableTools(EcorePrimitiveTypes.EFeatureMap chosenTools) {
	}

	/**
	 * 
	 */
	public void askForParentName() {
	}

	/**
	 * 
	 */
	public void chooseOptions() {
	}

	/**
	 * 
	 * @param toolsList 
	 */
	public void askForOtherTools(OptionableTool toolsList) {
	}

	/**
	 * 
	 */
	public void chooseMembership() {
	}

	/**
	 * 
	 */
	private void askForBrotherSisterName() {
	}

	/**
	 * 
	 */
	public void confirmSheet() {
	}

	/**
	 * 
	 */
	public void searchForMembership() {
	}

	/**
	 * 
	 */
	public void verifyMembership() {
	}

	/**
	 * 
	 * @param firstName 
	 * @param lastName 
	 */
	private void fillBrotherSisterName(String firstName, String lastName) {
	}

	/**
	 * 
	 * @param amount 
	 */
	private void fillContribution(float amount) {
	}

	/**
	 * 
	 */
	public void askForAddress() {
	}

	/**
	 * 
	 */
	public void askForBirthDate() {
	}

	/**
	 * 
	 */
	public void checkExistingStudent() {
	}

	/**
	 * 
	 */
	public void reuseSameSheet() {
	}

	/**
	 * 
	 * @param parentInformations 
	 */
	private void updateParentsInformations(EcorePrimitiveTypes.EMap parentInformations) {
	}

	/**
	 * 
	 */
	public void verifyFilledSheet() {
	}

	/**
	 * 
	 */
	public void askForParentsChanges() {
	}
};
